version: '3.8'

services:
  brave-mcp-server:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - REDIS_URL=redis://redis:6379
      - CACHE_ENABLED=true
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    command: pnpm run dev
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped

volumes:
  redis_dev_data: